[project]
name = "torch-hybrid-dyn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lviornery", email = "22897341+lviornery@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "bidict>=0.24.1",
    "torch>=2.14.1",
    "torchdiffeq",
]


[tool.uv.sources]
torchdiffeq = { git = "https://github.com/lviornery/torchdiffeq_initzero", rev = "04bae656f2f890504522d3b4fa73b01357a3b617" }

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
